api_platform:
    mapping:
        paths: ["%kernel.project_dir%/src/Entity"]
    swagger:
        versions: [3]
    patch_formats:
        json: ["application/merge-patch+json"]
    formats:
        jsonld: ["application/ld+json"]
        json: ["application/json"]
        html: ["text/html"]
    title: API Platform
    version: 1.0.0
    defaults:
        stateless: true
        pagination_client_items_per_page: true
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]
    collection:
        pagination:
            items_per_page_parameter_name: perPage
