services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: product_catalog_php
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        ports:
            - "8000:8000"
        environment:
            DATABASE_URL: mysql://symfony:symfony@db:3306/product_catalog
            MAILER_DSN: smtp://mailhog:1025
            MAILER_FROM: no-reply@product-catalog.test
            MAILER_INTERNAL: orders@product-catalog.test
            IMPORT_CSV: /var/www/html/var/data/products.csv

    db:
        image: mysql:8.0
        container_name: product_catalog_db
        restart: always
        environment:
            MYSQL_DATABASE: product_catalog
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql

    mailhog:
        image: mailhog/mailhog
        container_name: product_catalog_mailhog
        ports:
            - "1025:1025" # SMTP
            - "8025:8025" # Web UI (http://localhost:8025)

    node:
        image: node:18-alpine
        container_name: product_catalog_node
        working_dir: /app
        volumes:
            - .:/app
        command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 5173"
        ports:
            - "5173:5173"
        depends_on:
            - php

volumes:
    db_data: {}
